apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert
  labels:
    app: alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert
  template:
    metadata:
      labels:
        app: alert
    spec:
      containers:
        - name: alert
          image: "airport27/alert:latest"
          ports:
            - containerPort: 8084
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8084
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8084
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_PASSWORD
