apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
  labels:
    app: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member
          image: "jinsuheo/member:250827"
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: JWT_SECRET
            - name: CAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: CAPTCHA_SECRET
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: MAIL_PASSWORD
            - name: MANAGEMENT_HEALTH_MAIL_ENABLED
              value: "false"
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 150
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 150
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
