trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
  displayName: 'Install frontend dependencies'

- script: |
    cd frontend
    npm run build
  displayName: 'Build frontend'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure 구독 1 (2c387be4-0570-49f7-877a-d90c727fc3f4)'      # 실제 서비스 연결 이름으로 변경하세요
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload-batch \
        --account-name airportfrontendstorage \
        --source ./frontend/dist \
        --destination '$web' \
        --overwrite

      az cdn endpoint purge \
        --resource-group airport27-rsrcgrp \
        --profile-name airport \
        --name airport27 \
        --content-paths '/*'
  displayName: 'Deploy frontend and purge CDN'
