apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipmentanalysis
  labels:
    app: equipmentanalysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equipmentanalysis
  template:
    metadata:
      labels:
        app: equipmentanalysis
    spec:
      containers:
        - name: equipmentanalysis
          image: "jinsuheo/equipmentanalysis:250827"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_PASSWORD
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: GEMINI_API_KEY