apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipmentanalysis
  labels:
    app: equipmentanalysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equipmentanalysis
  template:
    metadata:
      labels:
        app: equipmentanalysis
    spec:
      containers:
        - name: equipmentanalysis
          image: "gangmin522/equipmentanalysis:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
