apiVersion: apps/v1
kind: Deployment
metadata:
  name: runwayobject
  labels:
    app: runwayobject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runwayobject
  template:
    metadata:
      labels:
        app: runwayobject
    spec:
      containers:
        - name: runwayobject
          image: "jinsuheo/runwayobject:250826"
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 150
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 150
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
