apiVersion: apps/v1
kind: Deployment
metadata:
  name: runwaycrack
  labels:
    app: runwaycrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runwaycrack
  template:
    metadata:
      labels:
        app: runwaycrack
    spec:
      containers:
        - name: runwaycrack
          image: "gangmin522/runwaycrack:latest"
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_PASSWORD
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: GEMINI_API_KEY
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
