apiVersion: v1
kind: Service
metadata:
  name: objectdectect-api
  labels:
    app: objectdectect-api
spec:
  type: ClusterIP
  selector:
    app: objectdectect-api
  ports:
    - port: 8000
      targetPort: 8000