server:
  port: 8088

jwt:
  secret: fmvqwnkeqnvkqweiscanjvdbqjedwqpdihccapdwqdjsac

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: member-unauthenticated
          uri: http://localhost:8082
          predicates:
            - Path=/user, /login/jwt
        - id: member-authenticated
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, /employees/**
          filters:
            - JwtFilter
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**
          filters:
            - JwtFilter
        - id: alert
          uri: http://localhost:8084
          predicates:
            - Path=/alerts/**, /cctvs/**
          filters:
            - JwtFilter
        - id: runwayobject
          uri: http://localhost:8085
          predicates:
            - Path=/strangeObjects/**, /workers/**, /workTrucks/**
          filters:
            - JwtFilter
        - id: runwaycrack
          uri: http://localhost:8086
          predicates:
            - Path=/runwayCracks/**, /runwayCrackReports/**
          filters:
            - JwtFilter
        - id: equipment analysis
          uri: http://localhost:8087
          predicates:
            - Path=/equipmentReports/**
          filters:
            - JwtFilter
        - id: equipmentdashboard
          uri: http://localhost:8088
          predicates:
            - Path=/equipment/**
          filters:
            - JwtFilter
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: member-unauthenticated
          uri: http://member:8080
          predicates:
            - Path=/user, /login/jwt
        - id: member-authenticated
          uri: http://member:8080
          predicates:
            - Path=/users/**, /employees/**
          filters:
            - JwtFilter
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**
          filters:
            - JwtFilter
        - id: alert
          uri: http://alert:8080
          predicates:
            - Path=/alerts/**, /cctvs/**
          filters:
            - JwtFilter
        - id: runwayobject
          uri: http://runwayobject:8080
          predicates:
            - Path=/strangeObjects/**, /workers/**, /workTrucks/**
          filters:
            - JwtFilter
        - id: runwaycrack
          uri: http://runwaycrack:8080
          predicates:
            - Path=/runwayCracks/**, /runwayCrackReports/**
          filters:
            - JwtFilter
        - id: equipment analysis
          uri: http://equipmentAnalysis:8080
          predicates:
            - Path=/equipmentReports/**
          filters:
            - JwtFilter
        - id: equipmentdashboard
          uri: http://equipmentdashboard:8080
          predicates:
            - Path=/equipment/**
          filters:
            - JwtFilter
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
