server:
  port: 8088

# 모든 프로필에 공통으로 적용될 JWT 설정
# 임의로 추가
jwt:
  secret: ${JWT_SECRET}


---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, /employees/**
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**
        - id: notification-websocket
          uri: ws://localhost:8083
          predicates:
            - Path=/notifications/ws/**
        - id: alert
          uri: http://localhost:8084
          predicates:
            - Path=/alerts/**, /cctvs/**
        - id: runwayobject
          uri: http://localhost:8085
          predicates:
            - Path=/strangeObjects/**, /workers/**, /workTrucks/**
        - id: runwaycrack
          uri: http://localhost:8086
          predicates:
            - Path=/runwaycracks/**, /runwaycrackreports/**
        - id: equipment-analysis
          uri: http://localhost:8087
          predicates:
            - Path=/equipmentReports/**
        - id: equipmentdashboard
          uri: http://localhost:8089
          predicates:
            - Path=/equipments/**
        - id: frontend
          uri: http://localhost:5173
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://fictional-space-fishstick-q7g77vvv7ww5c64w9-5173.app.github.dev/"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "X-Employee-Id"
              - "X-Authorities"
              - "Authorization"
              - "Content-Type"
              - "*"
            allowCredentials: true

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/users/**, /employees/**, /user, /login/jwt
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**
        - id: alert
          uri: http://alert:8080
          predicates:
            - Path=/alerts/**, /cctvs/**
        - id: runwayobject
          uri: http://runwayobject:8080
          predicates:
            - Path=/strangeObjects/**, /workers/**, /workTrucks/**
        - id: runwaycrack
          uri: http://runwaycrack:8080
          predicates:
            - Path=/runwaycracks/**, /runwaycrackreports/**
        - id: equipment-analysis
          uri: http://equipmentAnalysis:8080
          predicates:
            - Path=/equipmentReports/**
        - id: equipmentdashboard
          uri: http://equipmentdashboard:8080
          predicates:
            - Path=/equipment/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
