server:
  port: 8088

# 모든 프로필에 공통으로 적용될 JWT 설정
# 임의로 추가
jwt:
  secret: ${JWT_SECRET}


---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**, /api/employees/**
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/api/notifications/**
        - id: alert
          uri: http://localhost:8084
          predicates:
            - Path=/api/alerts/**, /api/cctvs/**
        - id: runwayobject
          uri: http://localhost:8085
          predicates:
            - Path=/api/strangeObjects/**, /api/workers/**, /api/workTrucks/**
        - id: objectdetect
          uri: http://localhost:8000
          predicates:
            - Path=/api/detect/**
        - id: runwaycrack-api
          uri: http://localhost:8001
          predicates:
            - Path=/api/runwaycracksDetect/**
        - id: runwaycrack
          uri: http://localhost:8086
          predicates:
            - Path=/api/runwaycracks/**, /api/runwaycrackreports/**
        - id: equipment-analysis
          uri: http://localhost:8087
          predicates:
            - Path=/api/equipmentReports/**
        - id: equipmentdashboard
          uri: http://localhost:8089
          predicates:
            - Path=/api/equipments/**, /api/equip/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://supreme-fiesta-97454xwqjrr7c7rxv-5173.app.github.dev/"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/api/users/**, /api/employees/**,
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/api/notifications/**
        - id: alert
          uri: http://alert:8080
          predicates:
            - Path=/api/alerts/**, /api/cctvs/**
        - id: runwayobject
          uri: http://runwayobject:8080
          predicates:
            - Path=/api/strangeObjects/**, /api/workers/**, /api/workTrucks/**
        - id: runwaycrack
          uri: http://runwaycrack:8080
          predicates:
            - Path=/api/runwaycracks/**, /api/runwaycrackreports/**
        - id: runwaycrack-api
          uri: http://runwaycrack-api:8000
          predicates:
            - Path=/api/runwaycracksDetect/**
        - id: objectdectect-api
          uri: http://objectdectect-api:8000
          predicates:
            - Path=/api/objectDetect/**
        - id: equipment-analysis
          uri: http://equipmentanalysis:8080
          predicates:
            - Path=/api/equipmentReports/**
        - id: equipmentdashboard
          uri: http://equipmentdashboard:8080
          predicates:
            - Path=/api/equipments/**, /api/equip/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://airport27.azureedge.net"
              - "https://airport27.azureedge.net"
              - "http://airport27-bgb3evepevfne3hf.z02.azurefd.net"
              - "https://airport27-bgb3evepevfne3hf.z02.azurefd.net"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
