apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: "jinsuheo/notification:2508271"
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: DB_PASSWORD
            - name: AZURE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: member-secrets
                  key: AZURE_ACCOUNT_KEY
            - name: STORAGE_ACCOUNT_NAME
              value: "airportcopy27"
            - name: STORAGE_CONTAINER_NAME
              value: "videos"
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 150
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 150
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5