apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: "gangmin522/notification:latest"
          ports:
            - containerPort: 8080
          env:
            - name: STORAGE_ACCOUNT_NAME
              value: "airportfrontendstorage"
            - name: CONTAINER_NAME
              value: "videos"
            - name: SAS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: SAS_TOKEN
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5